@startsalt lib_structure
{
    {T
        +domino_lib
        ++graphs
        +++generate
        +++generate_valid
        +++validate
        +++solve
        +++classify
        +++common
        +++graph_common
        ++lps
        +++mod
        +++execute_model
        ++++adapter
        ++++mod
        ++++parser
        ++++translator
        +++validate
        ++++model
        +++++bounds
        +++++helpers
        +++++mod
        +++++variables
        ++++mod
        ++types
        +++graph_types
        ++++graph
        ++++mod
        +++error
        +++mod
        ++lib
        ++tests
    }
}
@endsalt
