@startsalt lib_structure
{
    {T
        +lib
        ++graphs
        +++types
        ++++domino_types
        +++++error
        +++++tile
        +++++puzzle
        +++++solution
        ++++graph_types
        +++++orientation
        +++++direction
        +++++arc
        +++++graph
        +++functionalities
        ++++generate
        ++++validate
        ++++solve
        ++++classify
        ++++common
        ++++graph_common
        ++lps
        +++execute_model
        +++validate
    }
}
@endsalt